name: Spell Check

on:
  push:
    branches:
      - 'feature/**'
      - staging
      - Production
  pull_request:
    branches:
      - 'feature/**'
      - staging
      - Production

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Spell Checker
        uses: check-spelling/check-spelling@v0.0.24
        with:
          # point at your spelling config (optional)
          checkout: false
          config_path: .github/check-spelling.yml
